spring:
  application:
    name: padro
  security:
    user:
      name: ${AUTH_USERNAME:default-username}
      password: ${AUTH_PASSWORD:default-password}

management:
  endpoints:
    web:
      exposure:
        include: "health"

server:
  port: 8080

# Shared API Secret - Additional security layer
api:
  shared-secret: ${API_SHARED_SECRET:shared-secret}

padro:
  aytos-username: ${AYTOS_USERNAME:default-aytos-username}
  aytos-password: ${AYTOS_PASSWORD:default-aytos-password}
  aytos-soap-url: ${AYTOS_SOAP_URL:default-aytos-url}
  aytos-pub-key: ${AYTOS_PUB_KEY:default-aytos-key}
  aytos-refcat-url: ${AYTOS_REFCAT_URL:default-aytos-refcat-url}
  db-url: ${DB_URL:jdbc:h2:mem:padro-db}
  db-username: ${DB_USERNAME:sa}
  db-password: ${DB_PASSWORD:}

tributes:
  soap-url: ${TRIBUTES_SOAP_URL:default-tributes-url}
  soap-msg: ${TRIBUTES_SOAP_MSG:<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><Tributs xmlns="http://tempuri.org/"><IDEntitat>{municipio}</IDEntitat><IDUsuari>mtuson</IDUsuari><refCadastral>{ref_cad}</refCadastral></Tributs></soap:Body></soap:Envelope>}

transformations:
  municipalities: "{\"25110\":\"2511090004\"}"
