spring:
  application:
    name: padro
  security:
    user:
      name: ${AUTH_USERNAME:default-username}
      password: ${AUTH_PASSWORD:default-password}

management:
  endpoints:
    web:
      exposure:
        include: "health"

server:
  port: 8080

# Shared API Secret - Additional security layer
api:
  shared-secret: ${API_SHARED_SECRET:shared-secret}

padro:
  aytos-username: ${AYTOS_USERNAME:default-aytos-username}
  aytos-password: ${AYTOS_PASSWORD:default-aytos-password}
  aytos-soap-url: ${AYTOS_SOAP_URL:default-aytos-url}
  aytos-pub-key: ${AYTOS_PUB_KEY:default-aytos-key}
